### ISSUE TITLE
开启项目的时候报错   不支持的pname  没看到有配置的地方啊

### ISSUE THREAD

**Issue by liuxingyuxia** [we7coreteam/w7-rangine-project-document#12]
./bin/server start  报错
PHP Fatal error:  Uncaught ErrorException: unsupported option [pname] in @swoole-src/library/core/Server/Helper.php:160
Stack trace:
#0 [internal function]: W7\Core\Exception\HandlerExceptions->handleError()
#1 @swoole-src/library/core/Server/Helper.php(160): trigger_error()
#2 [internal function]: Swoole\Server\Helper::checkOptions()
#3 [internal function]: Swoole\Server\Port->set()
#4 /mnt/d/WWW/w7document-1.1.6/vendor/w7/rangine/Src/Http/Server/Server.php(48): Swoole\Server->set()
#5 /mnt/d/WWW/w7document-1.1.6/vendor/w7/rangine/Src/Console/Command/Server/ServerCommandAbstract.php(154): W7\Http\Server\Server->start()
#6 /mnt/d/WWW/w7document-1.1.6/vendor/w7/rangine/Src/Console/Command/Server/StartCommand.php(20): W7\Console\Command\Server\ServerCommandAbstract->start()
#7 /mnt/d/WWW/w7document-1.1.6/vendor/w7/rangine/Src/Console/Command/CommandAbstract.php(67): W7\Console\Command\Server\StartCommand->handle()
#8 /mnt/d/WWW/w7document-1.1.6/vendor/symfony/console/Command/Command.php(255): W7\Console\Command\CommandAbstract-> in @swoole-src/library/core/Server/Helper.php on line 160

**Comment by titrxw** [comment]
降低swoole版本到4.5.4及以下
